import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import {
  collectRefs,
  filePathForOperation,
  getOperation,
  isObjectLikeSchema,
  listOperations,
  operationName,
  parametersByLocation,
  parametersSchema,
  renderReferencedTypes,
  requestBodySchema,
  responseSchema,
  renderJsDoc,
  schemaToTs,
  toTypeName,
} from "./openapi.js";

export async function generateOne(spec, options) {
  const { method, operation } = getOperation(spec, options.path, options.method);
  const outputDir = resolve(process.cwd(), options.output);
  await mkdir(outputDir, { recursive: true });

  const fileName = filePathForOperation(options.path, method, operation);
  const file = join(outputDir, fileName);
  await writeFile(file, renderOperation(spec, options.path, method, operation), "utf8");

  return { count: 1, file };
}

export async function generateAll(spec, options) {
  const outputDir = resolve(process.cwd(), options.output);
  await mkdir(outputDir, { recursive: true });

  const operations = listOperations(spec);
  for (const item of operations) {
    const file = join(outputDir, filePathForOperation(item.path, item.method, item.operation));
    await writeFile(file, renderOperation(spec, item.path, item.method, item.operation), "utf8");
  }

  return { count: operations.length, dir: outputDir };
}

function renderOperation(spec, path, method, operation) {
  const name = operationName(method, path, operation);
  const typePrefix = toTypeName(name);
  const paramsSchema = parametersSchema(operation, ["path", "query"], spec);
  const bodySchema = requestBodySchema(operation);
  const resultSchema = responseSchema(operation);
  const pathParams = parametersByLocation(operation, "path");
  const queryParams = parametersByLocation(operation, "query");
  const queryObjectParam =
    pathParams.length === 0 &&
    queryParams.length === 1 &&
    isObjectLikeSchema(queryParams[0].schema, spec);
  const refs = new Set();

  collectRefs(paramsSchema, refs);
  collectRefs(bodySchema, refs);
  collectRefs(resultSchema, refs);

  const blocks = [
    "/* eslint-disable */",
    "// Generated by dm-api-tool. Do not edit manually.",
    "",
  ];

  const referencedTypes = renderReferencedTypes(spec, refs);
  if (referencedTypes) {
    blocks.push(referencedTypes, "");
  }

  blocks.push(renderNamedType(`${typePrefix}Params`, paramsSchema, spec, "Request params"));
  blocks.push(renderNamedType(`${typePrefix}Body`, bodySchema, spec, "Request body"));
  blocks.push(renderNamedType(`${typePrefix}Result`, resultSchema, spec, "Response data"));
  blocks.push("");
  blocks.push(
    renderFetchFunction({
      name,
      path,
      method,
      typePrefix,
      hasParams: Boolean(paramsSchema),
      hasBody: Boolean(bodySchema),
      pathParams,
      queryParams,
      queryObjectParam,
      operation,
    }),
  );

  return `${blocks.join("\n")}\n`;
}

function renderFetchFunction({
  name,
  path,
  method,
  typePrefix,
  hasParams,
  hasBody,
  pathParams,
  queryParams,
  queryObjectParam,
  operation,
}) {
  const args = [];
  if (hasParams) args.push(`params: ${typePrefix}Params`);
  if (hasBody) args.push(`body?: ${typePrefix}Body`);

  const pathTemplate = renderPathTemplate(path, pathParams);
  const queryBlock = renderQueryBlock(queryParams, queryObjectParam);
  const bodyBlock = hasBody
    ? `    body: body === undefined ? undefined : JSON.stringify(body),\n`
    : "";

  const doc = renderOperationDoc(operation, method, path);

  return `${doc}
export async function ${name}(${args.join(", ")}): Promise<${typePrefix}Result> {
  const pathname = ${pathTemplate};
${queryBlock}  const url = query ? \`\${pathname}?\${query}\` : pathname;
  const response = await fetch(url, {
    method: "${method.toUpperCase()}",
    headers: { "Content-Type": "application/json" },
${bodyBlock}  });

  if (!response.ok) {
    throw new Error(\`${method.toUpperCase()} ${path} failed: \${response.status}\`);
  }

  return response.json() as Promise<${typePrefix}Result>;
}`;
}

function renderNamedType(name, schema, spec, fallback) {
  const doc = renderJsDoc(schema);
  if (!doc.length) {
    doc.push("/**", ` * ${fallback}`, " */");
  }
  return `${doc.join("\n")}\nexport type ${name} = ${schemaToTs(schema, spec)};`;
}

function renderOperationDoc(operation, method, path) {
  const doc = renderJsDoc({
    summary: operation.summary,
    description: operation.description,
    deprecated: operation.deprecated,
  });
  const lines = doc.length ? doc.slice(0, -1) : ["/**"];
  lines.push(` * @endpoint ${method.toUpperCase()} ${path}`);
  if (operation.tags?.length) lines.push(` * @tags ${operation.tags.join(", ")}`);
  lines.push(" */");
  return lines.join("\n");
}

function renderPathTemplate(path, pathParams) {
  let template = path;
  for (const param of pathParams) {
    template = template.replace(
      `{${param.name}}`,
      `\${encodeURIComponent(String(params[${JSON.stringify(param.name)}]))}`,
    );
  }
  return `\`${template}\``;
}

function renderQueryBlock(queryParams, queryObjectParam) {
  if (!queryParams.length) {
    return "  const query = \"\";\n";
  }

  if (queryObjectParam) {
    return `  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params as Record<string, unknown>)) {
    if (value !== undefined && value !== null) search.set(key, String(value));
  }
  const query = search.toString();
`;
  }

  const lines = [
    "  const search = new URLSearchParams();",
    ...queryParams.map((param) => {
      const access = `params[${JSON.stringify(param.name)}]`;
      return `  if (${access} !== undefined) search.set("${param.name}", String(${access}));`;
    }),
    "  const query = search.toString();",
  ];

  return `${lines.join("\n")}\n`;
}
